webtalk_init -webtalk_dir /home/ko/Desktop/elec3342/mcdecoder/mcdecoder.sim/sim_1/behav/xsim/xsim.dir/test_SYMDET_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 19 14:52:09 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3286242" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "16496605-7ba9-443b-b8c0-d67c73c8cd5a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "69457726296b4ea2bb78d484392f4c3b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "188" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2000.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "17" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "107 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "26 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "524" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "17" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.10_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "307264_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3194557489 -regid "" -xml /home/ko/Desktop/elec3342/mcdecoder/mcdecoder.sim/sim_1/behav/xsim/xsim.dir/test_SYMDET_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ko/Desktop/elec3342/mcdecoder/mcdecoder.sim/sim_1/behav/xsim/xsim.dir/test_SYMDET_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ko/Desktop/elec3342/mcdecoder/mcdecoder.sim/sim_1/behav/xsim/xsim.dir/test_SYMDET_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
