#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Nov 09 20:53:42 CST 2021
# SW Build 3286242 on Wed Jul 28 13:09:46 MDT 2021
#
# IP Build 3279568 on Wed Jul 28 16:48:48 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_fifo_behav -key {Behavioral:sim_1:Functional:tb_fifo} -tclbatch tb_fifo.tcl -view /home/ko/Desktop/elec3342/mcdecoder/tb_uart_behav.wcfg -log simulate.log"
xsim tb_fifo_behav -key {Behavioral:sim_1:Functional:tb_fifo} -tclbatch tb_fifo.tcl -view /home/ko/Desktop/elec3342/mcdecoder/tb_uart_behav.wcfg -log simulate.log

